[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/index.html"

  [headers.values]
    pragma = 'no-cache'
    expires = '0'
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''